{
 "title": "K8s / Namespaces",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace:", "query": "label_values(namespace)" },
   {
    "name": "ingress",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\"}, ingress) "
   },
   {
    "name": "app",
    "label": "App:",
    "query": "label_values(kube_pod_labels{namespace=\"$namespace\"}, label_app_kubernetes_io_instance)"
   },
   {
    "name": "pod",
    "label": "Pod:",
    "query": "label_values({namespace=\"$namespace\", label_app_kubernetes_io_instance=~\"$app\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container:",
    "query": "label_values({namespace=\"$namespace\", container!=\"POD\", pod=~\"$pod\", label_app_kubernetes_io_instance=~\"$app\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{namespace=\"$namespace\", ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non 5xx responses)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=\"$namespace\", ingress=~\"$ingress\",status!~\"[5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{namespace=\"$namespace\", ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Pod memory usage (MB) ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace='$namespace', pod=~\"$pod\", container!=\"POD\", container!='', container=~\"$container\"}* on (pod) group_left(label_app_kubernetes_io_instance, namespace) kube_pod_labels{namespace='$namespace', label_app_kubernetes_io_instance=~'$app'}/1024/1024",
     "legendFormat": "{{container}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{namespace='$namespace', pod=~\"$pod\", container!='POD', container!='', container=~\"$container\"}[5m]) * on (pod) group_left(label_app_kubernetes_io_instance, namespace) kube_pod_labels{namespace='$namespace', label_app_kubernetes_io_instance=~'$app'} *1000",
     "legendFormat": "{{container}}:{{pod}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{namespace='$namespace', pod=~'$pod'}[5m]) * on (pod) group_left(label_app_kubernetes_io_instance, namespace) kube_pod_labels{namespace='$namespace', label_app_kubernetes_io_instance=~'$app'} / 1000",
     "legendFormat": "{{pod}}-{{interface}}-sent"
    },
    {
     "expr": "irate(container_network_receive_bytes_total{namespace='$namespace', pod=~'$pod'}[5m]) * on (pod) group_left(label_app_kubernetes_io_instance, namespace) kube_pod_labels{namespace='$namespace', label_app_kubernetes_io_instance=~'$app'} / 1000",
     "legendFormat": "{{pod}}-{{interface}}-received"
    }
   ]
  },
  {
   "title": "Number of restarts in 15 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "900*rate(kube_pod_container_status_restarts_total{namespace='$namespace', container_name!='POD', pod_name=~'$pod'}[15m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}