{{- if .CertManager.Enabled }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: infrastructure
spec:
  interval: 60m
  url: https://charts.jetstack.io
{{- end }}
