{{ if .sealedSecrets.enabled -}}
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: infrastructure
spec:
  interval: 60m
  url: https://bitnami-labs.github.io/sealed-secrets
{{- end }}
