{{ if or .loki.enabled .prometheus.enabled -}}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 10m
  values:
    sidecar:
      datasources:
        enabled: true
      dashboards:
        enabled: true
      notifiers:
        enabled: true
    {{- if .nginx.enabled }}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      {{- if .certManager.enabled }}
        cert-manager.io/cluster-issuer: letsencrypt
      tls:
        - secretName: tls-grafana
          hosts:
            - grafana.{{ .nginx.host }}
      {{- end }}
      hosts:
        - grafana.{{ .nginx.host }}
      path: /
    {{- end }}
{{- end }}
